class CABURNAY_ACTIVITY_IV {
    public static void main(String[] args) {
        int a = 4;
        int b = 9;
        int c = 6;

        int sum = a + b + c;
        int diff = a - b - c;
        int prod = a * b * c;
        int quot = a / b / c;

        System.out.println(sum);
        System.out.println(diff);
        System.out.println(prod);
        System.out.println(quot);
    }
}
