import java.util.Scanner;
class caburnay_activity_I {
    public static void main(String [ ] args) {
        Scanner sc = new Scanner (System.in);
        System.out.println(x: "Enter the color of the item: ");
        String color = "green";

        int color = "green";
        
        switch(color) {
        case 1:
            System.out.println("red");
            break;
        case 2:
            System.out.println("green");
            break;
        case 3:
            System.out.println("black"):
            break;
        }
    }
}
